"""Add PSU_id column in User

Revision ID: 1971ea3306f9
Revises: 611addcf017b
Create Date: 2023-04-10 17:13:53.098505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1971ea3306f9'
down_revision = '611addcf017b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PSU_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('PSU_id')

    # ### end Alembic commands ###
