"""Changing representation of user model

Revision ID: 55ba53269c43
Revises: 611addcf017b
Create Date: 2023-04-23 20:35:03.390334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ba53269c43'
down_revision = '611addcf017b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badge', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))
        batch_op.drop_column('can_delete')
        batch_op.drop_column('can_edit')
        batch_op.drop_column('can_add')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_add', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('can_edit', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('can_delete', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('role')
        batch_op.drop_column('badge')

    # ### end Alembic commands ###
