"""Add admin and manager classes

Revision ID: 611addcf017b
Revises: 9596a494d0bf
Create Date: 2023-02-23 19:30:47.241853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611addcf017b'
down_revision = '9596a494d0bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_edit', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_add', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_delete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('can_delete')
        batch_op.drop_column('can_add')
        batch_op.drop_column('can_edit')

    # ### end Alembic commands ###
