"""Added role field in User

Revision ID: 79048fbd75c8
Revises: 1971ea3306f9
Create Date: 2023-04-24 16:01:19.655083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79048fbd75c8'
down_revision = '1971ea3306f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
